### ISSUE TITLE
Expose FlexLexer.h

### ISSUE THREAD

**Issue by tsawada** [jmillikin/rules_flex#1]
Hi. Thanks for making & publishing this awesome rule!

I use flex within a genrule with `%option c++`, and generated code has `#include <FlexLexer.h>`.
It seems there's no easy way for subsequent `cc_binary` rule to find this header. Is it possible to have something like `@rules_flex//:flex_lexer_h` that can be added into `srcs` of `cc_binary` and `cc_library` so that these rules can find `FlexLexer.h` easily?

Thanks!

**Comment by jmillikin** [comment]
The `FlexLexer.h` file is different between versions of Flex, so you would need to extract it from the resolved toolchain.

For simple cases, please use `flex_cc_library` which handles the details:
```python
load("@rules_flex//flex:flex.bzl", "flex_cc_library")
flex_cc_library(
    name = "hello",
    src = "hello.l",
)
cc_binary(
    name = "hello_bin",
    deps = [":hello"],
)
```

**Comment by tsawada** [comment]
I think `flex` or `flex_cc_library` doesn't fit because In my usecase I need to patch .cpp file that flex generated before compiling them.
```
genrule(
    name = "flex_something",
    srcs = ["something.l"],
    outs = ["something_pre.yy.cpp"],
    cmd = "... $(FLEX) -o $@ $<",
    toolchains = ...
)

genrule(
    name = "patch_something",
    srcs = [":something_pre.yy.cpp"],
    outs = [":something.cpp"],
    cmd = "./patching_script < $< > $@",
)

cc_binary(
    name = "bin",
    srcs = ["something.cpp", "others.cpp"],
)
```

What do you recommend in such case?
As a dirty hack I also tried to extract `FlexLexer.h` in a `genrule(cmd="cp some/where", toolchains=["@flex//..."]) but couldn't find the file.

**Comment by jmillikin** [comment]
Hmm, there is not currently a good way to extract `FlexLexer.h` outside of the `flex_cc_library` rule. I will add one in the next release, which I'm planning to do after Bazel v0.29 is published.

Until then, please use the following workaround:
```python
# flex_lexer_h.bzl
load("@rules_flex//flex:flex.bzl", "flex_common")

def _flex_lexer_h(ctx):
    flex_toolchain = flex_common.flex_toolchain(ctx)
    flex_lexer_h = flex_toolchain.flex_lexer_h
    return CcInfo(compilation_context = cc_common.create_compilation_context(
        headers = depset(direct = [flex_lexer_h]),
        system_includes = depset(direct = [flex_lexer_h.dirname]),
    ))

flex_lexer_h = rule(_flex_lexer_h, toolchains = [
    flex_common.TOOLCHAIN_TYPE,
])
```

```python
load(":flex_lexer_h.bzl", "flex_lexer_h")
flex_lexer_h(name = "flex_lexer_h")
cc_binary(
    name = "bin",
    srcs = ["something.cpp", "others.cpp"],
    deps = [":flex_lexer_h"],
)
```

**Comment by tsawada** [comment]
The workaround worked perfectly. Thank you so much!
