### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by corco** [jmillikin/rules_flex#3]
Compiling flex fails on Windows. Is there any reason why Windows support was not implemented as for rules_m4 and rules_bison?

If it's possible to use gnulib to add support for Windows, I would gladly try to help to get it working.

**Comment by jmillikin** [comment]
GNU m4 and GNU Bison natively support compiling on Windows, to some extent, so to support them I needed to make only minimal changes. Flex does not build on Windows without extensive patches, so it's out of scope for these rules.

You may want to watch https://github.com/westes/flex/issues/367 for updates on upstreaming Windows support into Flex. When that lands, I will see if anything in rules_flex needs to change to support the Windows platform.

I strongly recommend against using gnulib, for this or for any other purpose. Substantially all of the challenges in writing Bazel rules for GNU m4 and GNU Bison were related to gnulib, and its design makes upgrading their versions extremely difficult.
