### ISSUE TITLE
Build fails with --incompatible_disallow_empty_glob

### ISSUE THREAD

**Issue by kkiningh** [jmillikin/rules_flex#4]
I get a build failure on master when building with the `--incompatible_disallow_empty_glob` flag. I think all that should be required to fix it is passing `allow_empty = True` to the globs on lines 30 and 35 of [repository.bzl](https://github.com/jmillikin/rules_flex/blob/0b4369cf6957de9718b9ad8b884a837d8220668f/flex/internal/repository.bzl#L30).

**Comment by jmillikin** [comment]
Thanks for the bug report! This should be fixed at HEAD.

Would you like a new `rules_flex` release, or are you fine with depending on a commit?

**Comment by kkiningh** [comment]
I'm fine with depending on a commit for now, thanks!
