### ISSUE TITLE
Visual Studio 2019/2022 support?

### ISSUE THREAD

**Issue by Vertexwahn** [jmillikin/rules_flex#8]
I did a `bazel build //...` on Windows 10 using Visual Studio 2019 (simialr behavoiur on Windows 11 with VS 2022). I get the following error message:

```
ERROR: C:/users/verte/_bazel_verte/tceazaz2/external/flex_v2.6.4/BUILD.bazel:20:11: Compiling src/options.c [for host] failed: (Exit 2): cl.exe failed: error executing command C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE ... (remaining 34 arguments skipped)
C:\users\verte\_bazel_verte\tceazaz2\execroot\rules_flex\external\flex_v2.6.4\src\flexdef.h(47): fatal error C1083: Cannot open include file: 'libgen.h': No such 
file or directory
INFO: Elapsed time: 12.773s, Critical Path: 7.69s
INFO: 268 processes: 156 internal, 112 local.
```

libgen.h is not available on Windows. Any hints on how I can get working these rule on Windows. Would like to use flex in a Bazel build that should work on macOS, Linux and Windows (using Visual Studio 2019/2022)

With VS 2022 on Windows 11 I get:

`C:\bazel_output_base\execroot\de_vertexwahn\external\flex_v2.6.4\src\flexdef.h(47): fatal error C1083: Cannot open include file: 'libgen.h': No such file or directory`

**Comment by jmillikin** [comment]
You may want to watch https://github.com/westes/flex/issues/367 for updates on upstreaming Windows support into Flex. When that lands, I will see if anything in rules_flex needs to change to support the Windows platform.
