### ISSUE TITLE
Typo in release announcment 0.2.1

### ISSUE THREAD

**Issue by hzeller** [jmillikin/rules_flex#9]
There are typos in the last release announcement: https://github.com/jmillikin/rules_flex/releases/tag/v0.2.1

 * There is a closing quote missing in the version number of `flex_register_toolchains()`
 * Unlike previous releases, the files are not named `rules_flex-v0.2.1.tar.xz`, but with an underscore in place of the dash before the version number: `rules_flex_v0.2.1.tar.xz`. The URL you mention uses the dash, yet the release tar filename comes with an underscore. I suspect it was meant to keep the dash in the release tar ?

**Comment by jmillikin** [comment]
Oops, thank you for catching that! I was using a new release script and didn't notice I'd bodged the filename formatting.
